[package]
name = "gmt-field-aberrations"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gmt-full-field-display", "gmt-point-field-display"]

[workspace.dependencies]
env_logger = "0.11.6"
skyangle = { version = "0.4.0", features = ["serde"] }
color-eyre = "0.6.3"
triangle-rs = "0.1.2"
serde-pickle = "1.2.0"
rayon = "1.10.0"
clap = { version = "4.5.50", features = ["derive"] }

[dependencies]
crseo = "2.5.2"
env_logger.workspace = true
geotrans = "1.0.0"
log = "0.4.25"
rson = "0.1.0"
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde-pickle.workspace = true
skyangle.workspace = true
thiserror = "2.0.11"
zernike = "0.2.1"
color-eyre.workspace = true
ron = "0.8.1"
rayon.workspace = true
anyhow = "1.0.100"

[dev-dependencies]
faer = "0.21.4"
triangle-rs.workspace = true
