[package]
name = "delrays"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
anyhow.workspace = true
crseo.workspace = true
faer = "0.24.4"
num-complex = "0.4"
plotters = "0.3.7"
serde.workspace = true
serde-pickle.workspace = true
skyangle.workspace = true
thiserror.workspace = true
triangle-rs.workspace = true
zernike = "0.2.2"
